//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AggregateMetotları_CountSumAvg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urunler
    {
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public string UrunMarka { get; set; }
        public int UrunFiyat { get; set; }
        public int UrunStok { get; set; }
    }
}
